/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "Sm2derSimplfied"
 * 	found in "module.asn1"
 */

#ifndef	_EccPublicKey_H_
#define	_EccPublicKey_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include "ObjID.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EccPublicKey */
typedef struct EccPublicKey {
	struct objIds {
		A_SEQUENCE_OF(ObjID_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} objIds;
	BIT_STRING_t	 eccPublicKey;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EccPublicKey_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EccPublicKey;

#ifdef __cplusplus
}
#endif

#endif	/* _EccPublicKey_H_ */
