/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "Sm2derSimplfied"
 * 	found in "module.asn1"
 */

#include <asn_internal.h>

#include "ECPrivateKey.h"

static asn_TYPE_member_t asn_MBR_ECPrivateKey_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ECPrivateKey, version),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"version"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ECPrivateKey, privateKey),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_SM2PrivateKey,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"privateKey"
		},
	{ ATF_POINTER, 1, offsetof(struct ECPrivateKey, parameters),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Parameters,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"parameters"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ECPrivateKey, publicKey),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_SM2PublicKey,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"publicKey"
		},
};
static ber_tlv_tag_t asn_DEF_ECPrivateKey_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_ECPrivateKey_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 1 }, /* version at 14 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, -1, 0 }, /* privateKey at 15 */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 2, 0, 0 }, /* parameters at 16 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 3, 0, 0 } /* publicKey at 18 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ECPrivateKey_specs_1 = {
	sizeof(struct ECPrivateKey),
	offsetof(struct ECPrivateKey, _asn_ctx),
	asn_MAP_ECPrivateKey_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ECPrivateKey = {
	"ECPrivateKey",
	"ECPrivateKey",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ECPrivateKey_tags_1,
	sizeof(asn_DEF_ECPrivateKey_tags_1)
		/sizeof(asn_DEF_ECPrivateKey_tags_1[0]), /* 1 */
	asn_DEF_ECPrivateKey_tags_1,	/* Same as above */
	sizeof(asn_DEF_ECPrivateKey_tags_1)
		/sizeof(asn_DEF_ECPrivateKey_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ECPrivateKey_1,
	4,	/* Elements count */
	&asn_SPC_ECPrivateKey_specs_1	/* Additional specs */
};

