/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "Sm2derSimplfied"
 * 	found in "module.asn1"
 */

#ifndef	_ObjectIdentifier_H_
#define	_ObjectIdentifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OBJECT_IDENTIFIER.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ObjectIdentifier */
typedef OBJECT_IDENTIFIER_t	 ObjectIdentifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ObjectIdentifier;
asn_struct_free_f ObjectIdentifier_free;
asn_struct_print_f ObjectIdentifier_print;
asn_constr_check_f ObjectIdentifier_constraint;
ber_type_decoder_f ObjectIdentifier_decode_ber;
der_type_encoder_f ObjectIdentifier_encode_der;
xer_type_decoder_f ObjectIdentifier_decode_xer;
xer_type_encoder_f ObjectIdentifier_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ObjectIdentifier_H_ */
