/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "Sm2derSimplfied"
 * 	found in "module.asn1"
 */

#ifndef	_Parameters_H_
#define	_Parameters_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ObjectIdentifier.h"
#include <NULL.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Parameters_PR {
	Parameters_PR_NOTHING,	/* No components present */
	Parameters_PR_namedCurve,
	Parameters_PR_implicitlyCA
} Parameters_PR;

/* Parameters */
typedef struct Parameters {
	Parameters_PR present;
	union Parameters_u {
		ObjectIdentifier_t	 namedCurve;
		NULL_t	 implicitlyCA;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Parameters_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Parameters;

#ifdef __cplusplus
}
#endif

#endif	/* _Parameters_H_ */
