/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "Sm2derSimplfied"
 * 	found in "module.asn1"
 */

#include <asn_internal.h>

#include "SM2Cipher.h"

static int
memb_hash_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size == 32)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_TYPE_member_t asn_MBR_SM2Cipher_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SM2Cipher, xCoordinate),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"xCoordinate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SM2Cipher, yCoordinate),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"yCoordinate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SM2Cipher, hash),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		memb_hash_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"hash"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SM2Cipher, cipher),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"cipher"
		},
};
static ber_tlv_tag_t asn_DEF_SM2Cipher_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_SM2Cipher_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 1 }, /* xCoordinate at 55 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, -1, 0 }, /* yCoordinate at 56 */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 2, 0, 1 }, /* hash at 57 */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 3, -1, 0 } /* cipher at 58 */
};
static asn_SEQUENCE_specifics_t asn_SPC_SM2Cipher_specs_1 = {
	sizeof(struct SM2Cipher),
	offsetof(struct SM2Cipher, _asn_ctx),
	asn_MAP_SM2Cipher_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SM2Cipher = {
	"SM2Cipher",
	"SM2Cipher",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SM2Cipher_tags_1,
	sizeof(asn_DEF_SM2Cipher_tags_1)
		/sizeof(asn_DEF_SM2Cipher_tags_1[0]), /* 1 */
	asn_DEF_SM2Cipher_tags_1,	/* Same as above */
	sizeof(asn_DEF_SM2Cipher_tags_1)
		/sizeof(asn_DEF_SM2Cipher_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SM2Cipher_1,
	4,	/* Elements count */
	&asn_SPC_SM2Cipher_specs_1	/* Additional specs */
};

