/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "Sm2derSimplfied"
 * 	found in "module.asn1"
 */

#ifndef	_SM2Cipher_H_
#define	_SM2Cipher_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SM2Cipher */
typedef struct SM2Cipher {
	INTEGER_t	 xCoordinate;
	INTEGER_t	 yCoordinate;
	OCTET_STRING_t	 hash;
	OCTET_STRING_t	 cipher;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SM2Cipher_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SM2Cipher;

#ifdef __cplusplus
}
#endif

#endif	/* _SM2Cipher_H_ */
