/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "Sm2derSimplfied"
 * 	found in "module.asn1"
 */

#ifndef	_SM2PublicKey_H_
#define	_SM2PublicKey_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SM2PublicKey */
typedef BIT_STRING_t	 SM2PublicKey_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SM2PublicKey;
asn_struct_free_f SM2PublicKey_free;
asn_struct_print_f SM2PublicKey_print;
asn_constr_check_f SM2PublicKey_constraint;
ber_type_decoder_f SM2PublicKey_decode_ber;
der_type_encoder_f SM2PublicKey_encode_der;
xer_type_decoder_f SM2PublicKey_decode_xer;
xer_type_encoder_f SM2PublicKey_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SM2PublicKey_H_ */
